#!/bin/bash

# Create Base Image

docker build -f Dockerfile-base . -t web_base

# Run docker-compose to build
docker-compose down --remove-orphans --rmi local
docker-compose build
# docker rmi $(docker images -a|grep "<none>"|awk '$1=="<none>" {print $3}') --force

# Run stack
docker-compose push
docker stack deploy --compose-file docker-compose.yml webappstack
docker service scale webappstack_clientapp=3 webappstack_nginx=3